### ISSUE TITLE
邮箱验证出错

### ISSUE THREAD

**Issue by limxc** [ldqk/Masuit.MyBlogs#16]
网站 163的邮箱不支持了嘛

**Comment by ldqk** [comment]
跟什么邮箱没关系的哦，邮箱规则在配置文件里面自行配置就好了

**Comment by limxc** [comment]
https://masuit.com/  这个网站回复的时候不能用163邮箱了,  没地方反馈就发这里了

**Comment by ldqk** [comment]
邮箱地址发一下，看看是不是规则误杀了

**Comment by limxc** [comment]
![image](https://user-images.githubusercontent.com/38428449/141677069-d23e7358-60b3-47ac-8d83-6750ed509edd.png)

**Comment by ldqk** [comment]
规则太严误杀了，已更正

**Comment by limxc** [comment]
提交的时候还是有验证..

**Comment by ldqk** [comment]
可以发验证码了呀

**Comment by limxc** [comment]
验证码可以了   提交的时候还有
![image](https://user-images.githubusercontent.com/38428449/141683843-d9da6770-c5c5-4543-b45b-7b6912dc68e0.png)

**Comment by ldqk** [comment]
你还是换个邮箱吧，不想调试规则了
