### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xcl-net** [ldqk/Masuit.MyBlogs#18]
**bug概要**
索引创建不成功;站点无法正常运行;
![image](https://user-images.githubusercontent.com/15728845/147022077-bd69760b-61af-4f97-9dc7-ecac00399a07.png)

**复现步骤**
1. 数据库导入mysql;
2. 项目编译成功;
3. 启动报错;

**预期的行为**

项目正常运行;

**Comment by ldqk** [comment]
数据库脚本每次release的时候才会更新，最新代码的话缺字段你手动补一下吧
