### ISSUE TITLE
[BUG]版本比较左侧内容出现两次

### ISSUE THREAD

**Issue by eddyyuen** [ldqk/Masuit.MyBlogs#19]
**bug概要**
版本比较时，左侧内容出现两次

**复现步骤**
1. [打开这个链接即可看到](https://ldqk.tk/1772/history/5168-5067)

**预期的行为**
左右内容对比

**屏幕截图**

**使用环境:**
 - OS: [windows 10]
 - Browser:  chrome

 

**附加的描述**

**Comment by ldqk** [comment]
感谢发现，模板内容重复渲染了，最新代码已提交，二进制文件下次release
