### ISSUE TITLE
老板，项目好久没更新了呢......

### ISSUE THREAD

**Issue by 172721404** [ldqk/Masuit.MyBlogs#2]
老板，项目好久没更新了呢......

**Comment by 172721404** [comment]
能提供最新的release版本吗？难得去编译了

**Comment by ldqk** [comment]
现在这个就是最新的代码，这几天没有功能更新

**Comment by 172721404** [comment]
我在蓉城呢  能发布下release吗？
![image](https://user-images.githubusercontent.com/19380127/66813029-91016080-ef66-11e9-9036-a8e23be71fbf.png)
博客的LOGO 不在了

**Comment by ldqk** [comment]
好的，下次提交代码我发一个编译好的包

**Comment by 172721404** [comment]
OK~~~牛掰
