### ISSUE TITLE
[BUG] 今天遇到一个奇怪的页面

### ISSUE THREAD

**Issue by JuneCandy** [ldqk/Masuit.MyBlogs#26]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

**bug概要**
我在网站搜索Hex-Rays，出来了两个搜索结果，第一个是我想要的 ，进入文章后，提示需要回复才能有下载内容，当我回复后，按F5刷新 直接返回404，并且搜搜结果也没有这个文章。文章标题我也没记，大概是 Hex-Rays  IDA
最后404的网址是: https://masuit.com/1990?kw=Hex-Rays&t=v7gjivwdxjwg

我进入这个文章后，提示需要回复才能看到下载链接，然后回复框也有很多人回复。因为网站一直都不需要回复就能下载，我就有点疑惑，又打开个浏览器窗口看一下其他文章有没有需要回复的，点开了两个，发现没有。我就想可能是这篇文章特殊的设定吧，就没多想。我继续点开其他文章也没有问题。现在我感觉很诡异。

**复现步骤**
1.无法复现

**预期的行为**

**屏幕截图**

**使用环境:**
 - OS: win10
 - Browser chrome
 - Version 105.0.5195.102

**附加的描述**

**Comment by ldqk** [comment]
这个链接有特殊的权限设定，出现404属于正常现象

**Comment by JuneCandy** [comment]
所以只有特别的人才能下载?
