### ISSUE TITLE
404页面的时候，赌猫的游戏玩不了[BUG]

### ISSUE THREAD

**Issue by CYL96** [ldqk/Masuit.MyBlogs#28]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

**bug概要**
本来想去看美女的写真的，结果进入404页面，然后页面后面的水波纹能生效，但是点击围堵猫猫游戏没有反应

**复现步骤**
1. Go to '[...](https://你的域名/1846?t=0HMRONGT5LI3B)'
2. Click on '点击小圆圈，堵住小猫'
3. See error

**预期的行为**
玩堵猫猫游戏

**屏幕截图**
![image](https://github.com/ldqk/Masuit.MyBlogs/assets/37651389/78914267-bb87-4c95-8407-9b6904596983)

**使用环境:**
 - OS: [e.g. iOS] windows10  22H2 19045.3086
 - Browser [e.g. chrome, safari] chrome  114.0.5735.199（正式版本） （64 位）

**Comment by ldqk** [comment]
感谢反馈，已修复。
另外，想看妹子的话，你得先在网站底部关闭安全模式，就可以了
