### ISSUE TITLE
请求添加新功能：windows访问的结果跟 mac 访问的结果不一样

### ISSUE THREAD

**Issue by wxpid1** [ldqk/Masuit.MyBlogs#29]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

请详细描述一下你想要的功能，实现什么效果？

**Comment by wxpid1** [comment]
我猜测是做软件类型过滤，但是可以不过滤吗？就是 有时候我 mac 上面还是要运行windows的软件的，不然还得开虚拟机的 windows 来访问，有时候架构也是，之前 x86 的都被过滤掉了，其实我 arm 的 mac 是可以运行 x86 的 windows 软件的。
如果不过滤那下载软件就方便多了，就不用用其他架构的系统电脑下载了。
或者 可以在界面上面选择自己需要的架构软件，再来做过滤也行。

**Comment by ldqk** [comment]
什么意思？
