### ISSUE TITLE
评论输入邮箱好像不支持一些别的或者“变体”的邮箱[BUG]

### ISSUE THREAD

**Issue by YeWenxuan64** [ldqk/Masuit.MyBlogs#30]
**bug概要**

**复现步骤**
1. Go to '评论区'
2. 写昵称、评论，填邮箱（我填的是foxmail.com，由qq邮箱注册。我的foxmail.com与qq.com域名不同但都是“同一个”邮箱）
3. click on '发送验证码'

**预期的行为**
用foxmail.com的邮箱可以发验证码，但实际上不行

**屏幕截图**
![image](https://github.com/ldqk/Masuit.MyBlogs/assets/60416781/8d7d0ee9-d0ae-491e-86f6-669844cffbef)

**使用环境:**
 - OS: [e.g. win nt10.0 win11]
 - Browser [e.g. chrome, edge]

**附加的描述**
我不懂，只是在写评论时看到了

**Comment by ldqk** [comment]
邮箱是白名单模式，foxmail.com已加入白名单
