### ISSUE TITLE
[BUG]无法编译

### ISSUE THREAD

**Issue by Lxc5211314** [ldqk/Masuit.MyBlogs#31]
无法编译，有几个项目没有
尽管可以手动引入包，但还是在这个项目集成比较好.....

![image](https://github.com/ldqk/Masuit.MyBlogs/assets/43310150/26586535-3da7-40a2-a7aa-c61db0b0b546)

**Comment by ldqk** [comment]
请先阅读项目readme的【项目部署】部分内容
