### ISSUE TITLE
[BUG]Counter.razor获取统计数据时有问题

### ISSUE THREAD

**Issue by christan-duplicate** [ldqk/Masuit.MyBlogs#32]
GetCounterPercent方法中，在没有数据的情况下，使用counters.Average会抛异常，建议先判断是Count>0后再使用Average

**Comment by ldqk** [comment]
这个小bug懒得修😂，正常情况下应用程序启动之后跑几秒钟后，就有数据计算了

**Comment by christan-duplicate** [comment]
debug时会一直没数据

**Comment by ldqk** [comment]
把https://github.com/ldqk/Masuit.MyBlogs/blob/master/src/Masuit.MyBlogs.Core/Common/PerfCounter.cs#L121 的`#if RELEASE`去掉即可

**Comment by christan-duplicate** [comment]
我加了个判断，现在正常了
