### ISSUE TITLE
Mysql 的建表语句还有吗

### ISSUE THREAD

**Issue by Qintai** [ldqk/Masuit.MyBlogs#33]
Mysql 的建表语句还有吗，本地没装  pg sql

**Comment by ldqk** [comment]
你把程序的驱动改成MySQL的，然后跑一下就自动生成表结构了

**Comment by Qintai** [comment]
![image](https://github.com/ldqk/Masuit.MyBlogs/assets/55422114/74f947ea-e24e-4afc-8cb7-bf876148869d)
这里写死了 pgsql。修改程序驱动是改这里嘛，加个UseMySQL
```
 services.AddDbContext<LoggerDbContext>(opt => opt.UseNpgsql(AppConfig.ConnString)); //配置数据库
```

**Comment by Qintai** [comment]
![image](https://github.com/ldqk/Masuit.MyBlogs/assets/55422114/74f947ea-e24e-4afc-8cb7-bf876148869d)
这里写死了 pgsql。修改程序驱动是改这里嘛，加个UseMySQL
```
 services.AddDbContext<LoggerDbContext>(opt => opt.UseNpgsql(AppConfig.ConnString)); //配置数据库
```

**Comment by ldqk** [comment]
是的，你引用MySQL的驱动改成UseMySQL，连接字符串也改成MySQL的就好了
