### ISSUE TITLE
net461版下的bug

### ISSUE THREAD

**Issue by yxAaron** [ldqk/Masuit.MyBlogs#4]
你好，我在学习使用此项目的net461版本，在SystemController这个控制器下，GetBaseInfo这个action 下返回数据中的
ToJsonStringAsync()方法报错，我使用nuget引用了最新的Masuit.Tools，在tool里面并没有找到这个方法

![@1(`I0CRD T88 OVE5~GKIH](https://user-images.githubusercontent.com/11607552/87409594-bacfdc80-c5f7-11ea-92b6-6f46330469a0.png)

**Comment by ldqk** [comment]
你好，net461版本的迁移至.net core后就已经不再维护了，建议拉取最新的master的代码进行构建。
