### ISSUE TITLE
net5版本编译运行问题

### ISSUE THREAD

**Issue by brack7n** [ldqk/Masuit.MyBlogs#8]
你好，我在本地尝试构建运行，使用vs2019+Mysql8.0。
 编译成功后运行访问网站主页提示以下错误： 
<img width="1346" alt="1" src="https://user-images.githubusercontent.com/28703863/106376109-ec11cd80-63cc-11eb-8796-9385c5035f57.png">

修改报错语句赋值为"Description"字符串后再次运行

<img width="1422" alt="2" src="https://user-images.githubusercontent.com/28703863/106376130-1a8fa880-63cd-11eb-98c0-5040e54db875.png">

查看数据库中所有表的数据为空

**Comment by ldqk** [comment]
你需要先导入数据库脚本
